/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.frames.guia1;

import java.awt.event.KeyEvent;
import java.text.DecimalFormat;
import javax.swing.JFrame;

/**
 *
 * @author arman
 */
public class frmEjercicio2 extends javax.swing.JFrame {

    
    DecimalFormat formato=new DecimalFormat("0.00");
    /**
     * Creates new form frmEjercicio2
     */
    public frmEjercicio2() {
        initComponents();
        setLocationRelativeTo(null);
        rdRadio.setSelected(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        rdGroup = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtCircunferencia = new javax.swing.JTextField();
        txtRadio = new javax.swing.JTextField();
        btnCalcular = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        txtDiametro = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txtCircunferenciaRadio = new javax.swing.JTextField();
        rdRadio = new javax.swing.JRadioButton();
        rdDiametro = new javax.swing.JRadioButton();
        btReset = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setText("Calcular circunferencia");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 0, -1, -1));

        jLabel2.setText("Ingrese radio:");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 70, -1, -1));

        jLabel3.setText("Circunferencia con diametro:");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 70, -1, -1));

        txtCircunferencia.setEditable(false);
        txtCircunferencia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCircunferenciaActionPerformed(evt);
            }
        });
        getContentPane().add(txtCircunferencia, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 60, 120, -1));

        txtRadio.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtRadioKeyTyped(evt);
            }
        });
        getContentPane().add(txtRadio, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 60, 120, -1));

        btnCalcular.setText("Calcular");
        btnCalcular.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCalcularActionPerformed(evt);
            }
        });
        getContentPane().add(btnCalcular, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 160, -1, -1));

        jLabel4.setText("Ingrese diametro:");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 110, -1, -1));

        txtDiametro.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtDiametroKeyTyped(evt);
            }
        });
        getContentPane().add(txtDiametro, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 100, 120, -1));

        jLabel5.setText("Circunferencia con radio:");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 110, 160, 20));

        txtCircunferenciaRadio.setEditable(false);
        txtCircunferenciaRadio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCircunferenciaRadioActionPerformed(evt);
            }
        });
        getContentPane().add(txtCircunferenciaRadio, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 110, 120, -1));

        rdGroup.add(rdRadio);
        rdRadio.setText("Radio");
        rdRadio.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                rdRadioStateChanged(evt);
            }
        });
        rdRadio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rdRadioActionPerformed(evt);
            }
        });
        getContentPane().add(rdRadio, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 30, -1, -1));

        rdGroup.add(rdDiametro);
        rdDiametro.setText("Diametro");
        rdDiametro.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                rdDiametroStateChanged(evt);
            }
        });
        rdDiametro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rdDiametroActionPerformed(evt);
            }
        });
        getContentPane().add(rdDiametro, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 30, -1, -1));

        btReset.setText("Limpiar");
        btReset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btResetActionPerformed(evt);
            }
        });
        getContentPane().add(btReset, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 160, -1, -1));

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/recursos/iconos/back.png"))); // NOI18N
        jLabel6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel6MouseClicked(evt);
            }
        });
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCalcularActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCalcularActionPerformed
        
        
        
        double resultador;
        double resultadod;
        
        
        if (rdRadio.isSelected()==true) {
            double radio=Double.parseDouble(txtRadio.getText());
           resultador=Math.PI*radio*2;
        txtCircunferenciaRadio.setText(formato.format(resultador)+""); 
        }
        if (rdDiametro.isSelected()==true) {
            double diametro=Double.parseDouble(txtDiametro.getText());
            resultadod=Math.PI*diametro;
        txtCircunferencia.setText(formato.format(resultadod)+"");
        }
 
    }//GEN-LAST:event_btnCalcularActionPerformed

    private void txtCircunferenciaRadioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCircunferenciaRadioActionPerformed
        
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCircunferenciaRadioActionPerformed

    private void rdRadioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rdRadioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rdRadioActionPerformed

    private void rdDiametroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rdDiametroActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rdDiametroActionPerformed

    private void rdRadioStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_rdRadioStateChanged
        if (rdRadio.isSelected()) {
            txtDiametro.setEnabled(false);
            txtCircunferencia.setEnabled(false);
            txtDiametro.setText("");
            txtRadio.requestFocus();
       }
        else{
            txtDiametro.setEnabled(true);
            txtCircunferencia.setEnabled(true);
        }
    }//GEN-LAST:event_rdRadioStateChanged

    private void rdDiametroStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_rdDiametroStateChanged
        if (rdDiametro.isSelected()) {
            txtRadio.setEnabled(false);
            txtCircunferenciaRadio.setEnabled(false);
            txtRadio.setText("");
            txtDiametro.requestFocus();
        }
        else{
            txtRadio.setEnabled(true);
            txtCircunferenciaRadio.setEnabled(true);
        }
    }//GEN-LAST:event_rdDiametroStateChanged

    private void btResetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btResetActionPerformed
       txtCircunferencia.setText("");
       txtCircunferenciaRadio.setText("");
       txtDiametro.setText("");
       txtRadio.setText("");
    }//GEN-LAST:event_btResetActionPerformed

    private void txtCircunferenciaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCircunferenciaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCircunferenciaActionPerformed

    private void txtRadioKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtRadioKeyTyped
        int c=(int) evt.getKeyChar();

        if ((c >=48 && c<=57)  || (c==46) || (c==8) || (c== (char)KeyEvent.VK_BACK_SPACE) || (c== (char)KeyEvent.VK_ENTER)) {
            if (c==46) {
                String cadena=txtRadio.getText();
                int tamanio=cadena.length();
                for (int i = 0; i <= tamanio; i++) {
                    if (cadena.contains(".")) {
                        evt.setKeyChar((char) KeyEvent.VK_CLEAR);
                        getToolkit().beep();
                        evt.consume();
                    }
                }
            }
        }else{
            evt.setKeyChar((char) KeyEvent.VK_CLEAR);
            getToolkit().beep();
            evt.consume();
        }
    }//GEN-LAST:event_txtRadioKeyTyped

    private void txtDiametroKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtDiametroKeyTyped
        int c=(int) evt.getKeyChar();

        if ((c >=48 && c<=57)  || (c==46) || (c==8) || (c== (char)KeyEvent.VK_BACK_SPACE) || (c== (char)KeyEvent.VK_ENTER)) {
            if (c==46) {
                String cadena=txtDiametro.getText();
                int tamanio=cadena.length();
                for (int i = 0; i <= tamanio; i++) {
                    if (cadena.contains(".")) {
                        evt.setKeyChar((char) KeyEvent.VK_CLEAR);
                        getToolkit().beep();
                        evt.consume();
                    }
                }
            }
        }else{
            evt.setKeyChar((char) KeyEvent.VK_CLEAR);
            getToolkit().beep();
            evt.consume();
        }
    }//GEN-LAST:event_txtDiametroKeyTyped

    private void jLabel6MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel6MouseClicked
        frmOpcionesGuia1 op=new frmOpcionesGuia1();
        op.setVisible(true);
        this.setVisible(false);
        this.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
    }//GEN-LAST:event_jLabel6MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmEjercicio2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmEjercicio2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmEjercicio2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmEjercicio2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmEjercicio2().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btReset;
    private javax.swing.JButton btnCalcular;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JRadioButton rdDiametro;
    private javax.swing.ButtonGroup rdGroup;
    private javax.swing.JRadioButton rdRadio;
    private javax.swing.JTextField txtCircunferencia;
    private javax.swing.JTextField txtCircunferenciaRadio;
    private javax.swing.JTextField txtDiametro;
    private javax.swing.JTextField txtRadio;
    // End of variables declaration//GEN-END:variables
}
